```mermaid
stateDiagram-v2
    Hunting --> Wandering : Hunts Successfully<br/>Or Prey Escaped
    Hunting --> Fleeing : Sees More<br/>Powerful Enemy
    Wandering --> Hunting : Sees Weaker Prey

    [*] --> Wandering
    Foraging --> Wandering : Consumed<br/>Energy
    Wandering --> Foraging : Energy < 120 & <br/>Detects Energy
    Foraging --> Fleeing : Sees More<br/>Powerful Enemy

    Wandering --> Fleeing : Sees More<br/>Powerful Enemy
    Fleeing --> Wandering : Enemy No Longer<br/>In View

    Wandering --> Mating : Energy > 80 & <br/>Detects Same Species
    Mating --> Wandering : Finished<br/>Mating
    Mating --> Fleeing : Sees More<br/>Powerful Enemy
```