
stateDiagram-v2
    [*] --> Wandering
    
    Hunting --> Wandering : Prey Eaten
    Hunting --> Fleeing : Detects Predator
    Wandering --> Hunting : Energy > 125 &\nDetects Prey

    Foraging --> Wandering : Consumed Energy & \nMovement Stopped
    Wandering --> Foraging : Energy <= 350 & <br/>Detects Energy
    Foraging --> Fleeing : Detects Predator

    Wandering --> Fleeing : Detects Predator
    Fleeing --> Wandering : Distance to Predator > 12f

    Wandering --> Mating : Energy > 125 & <br/>Detects Mate
    Mating --> Wandering : Finished<br/>Mating
    Mating --> Fleeing : Detects Predator
